name: Systems Monitoring

on:
  schedule:
    - cron: "18/5 * * * *"

jobs:
  URL_Health_Check:
    runs-on: ubuntu-20.04
    steps:
      - uses: Jtalk/url-health-check-action@v4
        with:
          url: https://fso-pokedex-rednaxelam.fly.dev/|https://pokeapi.co/api/v2/pokemon/?limit=50|https://pokeapi.co/api/v2/pokemon/kakuna
          max-attempts: 3
          retry-delay: 15s
          retry-all: true
