name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SKIP_CONDITION: ${{ github.event.commits == null || contains(github.event.commits[0].message, '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run tests
        run: npm run test
      - name: Build
        run: npm run build
      # - name: e2e tests
      #   uses: cypress-io/github-action@v5
      #   with:
      #     command: npm run test:e2e
      #     start: npm run start-prod
      #     wait-on: http://localhost:5000
      # - name: set up for deployment
      #   if: ${{ github.event_name == 'push' && env.SKIP_CONDITION == 'false'}}
      #   uses: superfly/flyctl-actions/setup-flyctl@master
      # - name: deploy app
      #   if: ${{ github.event_name == 'push' && env.SKIP_CONDITION == 'false'}}
      #   run: flyctl deploy --remote-only
      #   env:
      #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: discord failure reporting
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: ${{ github.event_name == 'push' && env.SKIP_CONDITION == 'false' && failure()}}
        with:
          severity: error
          details: commit ${{ github.event.commits.url }} by ${{ github.event.commits.committer.username }} broke the build ._.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    outputs:
      SKIP_CONDITION: ${{ env.SKIP_CONDITION }}
  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.event_name == 'push' && needs.simple_deployment_pipeline.outputs.SKIP_CONDITION == 'false'}}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      # - name: Bump version and push tag
      #   uses: anothrNick/github-tag-action@777684df761b882a3f4f70db16ac70d8cc78d0ea
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     DEFAULT_BUMP: patch
      - name: discord failure reporting
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: ${{ github.event_name == 'push' && needs.simple_deployment_pipeline.outputs.SKIP_CONDITION == 'false' && failure()}}
        with:
          severity: error
          details: commit ${{ github.event.commits.url }} by ${{ github.event.commits.committer.username }} broke the build ._.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: discord success reporting
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: ${{ github.event_name == 'push' && needs.simple_deployment_pipeline.outputs.SKIP_CONDITION == 'false' && success() }}
        with:
          severity: info
          details: a new version of pokedex was deployed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}